In [1]:
import pandas as pd
import numpy as np


#data = pd.read_csv('labelled_training_data.csv')
data = pd.read_csv('labelled_testing_data.csv')
validation_df = pd.read_csv('labelled_validation_data.csv')


In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
data.head()

timestamp  processId  threadId  parentProcessId  userId  mountNamespace  \
0  129.050634        382       382                1     101      4026532232   
1  129.051238        379       379                1     100      4026532231   
2  129.051434          1         1                0       0      4026531840   
3  129.051481          1         1                0       0      4026531840   
4  129.051522          1         1                0       0      4026531840   

       processName         hostName  eventId           eventName  \
0  systemd-resolve  ip-10-100-1-217       41              socket   
1  systemd-network  ip-10-100-1-217       41              socket   
2          systemd  ip-10-100-1-217     1005  security_file_open   
3          systemd  ip-10-100-1-217      257              openat   
4          systemd  ip-10-100-1-217        5               fstat   

                                      stackAddresses  argsNum  returnValue  \
0  [140159195621643, 140159192455417, 94656731598...        3           15   
1  [139853228042507, 93935071185801, 93935080775184]        3           15   
2             [140362867191588, 8103505641674583858]        4            0   
3                                                 []        4           17   
4                                  [140362867189385]        2            0   

                                                args  sus  evil  
0  [{'name': 'domain', 'type': 'int', 'value': 'A...    0     0  
1  [{'name': 'domain', 'type': 'int', 'value': 'A...    0     0  
2  [{'name': 'pathname', 'type': 'const char*', '...    0     0  
3  [{'name': 'dirfd', 'type': 'int', 'value': -10...    0     0  
4  [{'name': 'fd', 'type': 'int', 'value': 17}, {...    0     0

In [4]:
data.corr()

timestamp  processId  threadId  parentProcessId    userId  \
timestamp         1.000000   0.491130  0.491046         0.669917  0.683395   
processId         0.491130   1.000000  0.999478         0.580795  0.403193   
threadId          0.491046   0.999478  1.000000         0.580544  0.403018   
parentProcessId   0.669917   0.580795  0.580544         1.000000  0.546944   
userId            0.683395   0.403193  0.403018         0.546944  1.000000   
mountNamespace   -0.136004  -0.258951 -0.259253        -0.146671 -0.097958   
eventId          -0.363611  -0.189331 -0.189118        -0.310943 -0.394549   
argsNum           0.160854   0.114630  0.114770         0.145170  0.202659   
returnValue      -0.100886  -0.051313 -0.051281        -0.075827 -0.123286   
sus               0.623884   0.481307  0.481022         0.691091  0.770550   
evil              0.701631   0.411276  0.411148         0.716143  0.898078   

                 mountNamespace   eventId   argsNum  returnValue       sus  \
timestamp             -0.136004 -0.363611  0.160854    -0.100886  0.623884   
processId             -0.258951 -0.189331  0.114630    -0.051313  0.481307   
threadId              -0.259253 -0.189118  0.114770    -0.051281  0.481022   
parentProcessId       -0.146671 -0.310943  0.145170    -0.075827  0.691091   
userId                -0.097958 -0.394549  0.202659    -0.123286  0.770550   
mountNamespace         1.000000  0.027708 -0.032858     0.008023 -0.130868   
eventId                0.027708  1.000000  0.364773     0.051660 -0.345232   
argsNum               -0.032858  0.364773  1.000000     0.080533  0.129866   
returnValue            0.008023  0.051660  0.080533     1.000000 -0.103648   
sus                   -0.130868 -0.345232  0.129866    -0.103648  1.000000   
evil                  -0.095256 -0.375582  0.229034    -0.127150  0.727881   

                     evil  
timestamp        0.701631  
processId        0.411276  
threadId         0.411148  
parentProcessId  0.716143  
userId           0.898078  
mountNamespace  -0.095256  
eventId         -0.375582  
argsNum          0.229034  
returnValue     -0.127150  
sus              0.727881  
evil             1.000000

In [5]:
data.cov()

timestamp     processId      threadId  parentProcessId  \
timestamp         3822.231471  3.370046e+04  3.365719e+04     8.170017e+04   
processId        33700.460280  1.231860e+06  1.229847e+06     1.271591e+06   
threadId         33657.194051  1.229847e+06  1.229119e+06     1.269626e+06   
parentProcessId  81700.170185  1.271591e+06  1.269626e+06     3.891235e+06   
userId           14950.612569  1.583516e+05  1.581067e+05     3.817819e+05   
mountNamespace    -152.289786 -5.205509e+03 -5.205779e+03    -5.240258e+03   
eventId          -4476.591050 -4.184613e+04 -4.175237e+04    -1.221453e+05   
argsNum              6.345497  8.118066e+01  8.118939e+01     1.827236e+02   
returnValue      -2303.030885 -2.102908e+04 -2.099259e+04    -5.523009e+04   
sus                 11.183462  1.548874e+02  1.546235e+02     3.952688e+02   
evil                15.966252  1.680158e+02  1.677765e+02     5.199707e+02   

                        userId  mountNamespace        eventId     argsNum  \
timestamp         14950.612569     -152.289786   -4476.591050    6.345497   
processId        158351.575444    -5205.509149  -41846.131354   81.180665   
threadId         158106.675407    -5205.779462  -41752.373774   81.189387   
parentProcessId  381781.927518    -5240.258098 -122145.344112  182.723633   
userId           125215.402960     -627.812615  -27802.352718   45.758170   
mountNamespace     -627.812615      328.043714      99.932795   -0.379730   
eventId          -27802.352718       99.932795   39655.568306   46.349979   
argsNum              45.758170       -0.379730      46.349979    0.407145   
returnValue      -16108.466592       53.655710    3798.503444   18.973879   
sus                  79.057502       -0.687241     -19.933200    0.024026   
evil                116.971068       -0.635026     -27.529126    0.053791   

                   returnValue         sus        evil  
timestamp         -2303.030885   11.183462   15.966252  
processId        -21029.075820  154.887436  168.015778  
threadId         -20992.592757  154.623544  167.776490  
parentProcessId  -55230.093998  395.268793  519.970731  
userId           -16108.466592   79.057502  116.971068  
mountNamespace       53.655710   -0.687241   -0.635026  
eventId            3798.503444  -19.933200  -27.529126  
argsNum              18.973879    0.024026    0.053791  
returnValue      136338.993279  -11.096429  -17.280753  
sus                 -11.096429    0.084067    0.077680  
evil                -17.280753    0.077680    0.135479

In [6]:
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline    

In [7]:
"""
plt.matshow(data.corr(), cmap = "summer")                    
plt.colorbar()
plt.xticks(list(range(len(data.columns))), data.columns, rotation = 'vertical')
plt.yticks(list(range(len(data.columns))), data.columns, rotation = 'horizontal')
plt.show()

sb.set(rc = {'figure.figsize':(16,10)})
sb.heatmap(data.corr(),annot=True, cmap="Greens")


plt.savefig('Heatmap(2)',dpi=500)
"""

'\nplt.matshow(data.corr(), cmap = "summer")                    \nplt.colorbar()\nplt.xticks(list(range(len(data.columns))), data.columns, rotation = \'vertical\')\nplt.yticks(list(range(len(data.columns))), data.columns, rotation = \'horizontal\')\nplt.show()\n\nsb.set(rc = {\'figure.figsize\':(16,10)})\nsb.heatmap(data.corr(),annot=True, cmap="Greens")\n\n\nplt.savefig(\'Heatmap(2)\',dpi=500)\n'

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188967 entries, 0 to 188966
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   timestamp        188967 non-null  float64
 1   processId        188967 non-null  int64  
 2   threadId         188967 non-null  int64  
 3   parentProcessId  188967 non-null  int64  
 4   userId           188967 non-null  int64  
 5   mountNamespace   188967 non-null  int64  
 6   processName      188967 non-null  object 
 7   hostName         188967 non-null  object 
 8   eventId          188967 non-null  int64  
 9   eventName        188967 non-null  object 
 10  stackAddresses   188967 non-null  object 
 11  argsNum          188967 non-null  int64  
 12  returnValue      188967 non-null  int64  
 13  args             188967 non-null  object 
 14  sus              188967 non-null  int64  
 15  evil             188967 non-null  int64  
dtypes: float64(1), int64(10), object(5)
me

In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data['processName'] = le.fit_transform(data['processName'])
data['eventName'] = le.fit_transform(data['eventName'])
data['stackAddresses'] = le.fit_transform(data['stackAddresses'])
data['args'] = le.fit_transform(data['args'])

In [10]:
data

timestamp  processId  threadId  parentProcessId  userId  \
0       129.050634        382       382                1     101   
1       129.051238        379       379                1     100   
2       129.051434          1         1                0       0   
3       129.051481          1         1                0       0   
4       129.051522          1         1                0       0   
...            ...        ...       ...              ...     ...   
188962  496.629003       7555      7555             7548    1001   
188963  496.629025       7555      7555             7548    1001   
188964  496.629047       7555      7555             7548    1001   
188965  496.629069       7555      7555             7548    1001   
188966  496.629091       7555      7555             7548    1001   

        mountNamespace  processName         hostName  eventId  eventName  \
0           4026532232           78  ip-10-100-1-217       41         40   
1           4026532231           77  ip-10-100-1-217       41         40   
2           4026531840           73  ip-10-100-1-217     1005         32   
3           4026531840           73  ip-10-100-1-217      257         28   
4           4026531840           73  ip-10-100-1-217        5         17   
...                ...          ...              ...      ...        ...   
188962      4026531840          233  ip-10-100-1-217       42          9   
188963      4026531840          233  ip-10-100-1-217       42          9   
188964      4026531840          233  ip-10-100-1-217       42          9   
188965      4026531840          233  ip-10-100-1-217       42          9   
188966      4026531840          233  ip-10-100-1-217       42          9   

        stackAddresses  argsNum  returnValue   args  sus  evil  
0                 1601        3           15   6912    0     0  
1                 1158        3           15   6912    0     0  
2                 2206        4            0  12213    0     0  
3                 4195        4           17   2628    0     0  
4                 2159        2            0   7099    0     0  
...                ...      ...          ...    ...  ...   ...  
188962            4195        3         -114  25342    1     1  
188963            4195        3         -114  25363    1     1  
188964            4195        3         -114  25385    1     1  
188965            4195        3         -114  25407    1     1  
188966            4195        3         -114  25427    1     1  

[188967 rows x 16 columns]

In [11]:
#data.to_csv("Beth_for_XAI.csv")

In [12]:
print(data['sus'].value_counts())

1    171459
0     17508
Name: sus, dtype: int64


In [13]:
print(data['evil'].value_counts())

1    158432
0     30535
Name: evil, dtype: int64


In [14]:
data.describe()

timestamp      processId       threadId  parentProcessId  \
count  188967.000000  188967.000000  188967.000000    188967.000000   
mean      455.070015    7347.397202    7347.754089      6919.593490   
std        61.824198    1109.892047    1108.656349      1972.621259   
min       129.050634       1.000000       1.000000         0.000000   
25%       461.577225    7555.000000    7555.000000      7548.000000   
50%       470.889349    7555.000000    7555.000000      7548.000000   
75%       487.116843    7555.000000    7555.000000      7548.000000   
max       496.629091    7555.000000    7705.000000      7552.000000   

              userId  mountNamespace    processName        eventId  \
count  188967.000000    1.889670e+05  188967.000000  188967.000000   
mean      854.301682    4.026532e+09     197.949123      88.802198   
std       353.857885    1.811198e+01      71.176493     199.137059   
min         0.000000    4.026532e+09       0.000000       2.000000   
25%      1001.000000    4.026532e+09     233.000000      42.000000   
50%      1001.000000    4.026532e+09     233.000000      42.000000   
75%      1001.000000    4.026532e+09     233.000000      42.000000   
max      1001.000000    4.026532e+09     243.000000    1010.000000   

           eventName  stackAddresses        argsNum    returnValue  \
count  188967.000000   188967.000000  188967.000000  188967.000000   
mean       12.341007     4107.200638       2.894569     -66.556991   
std         8.469662      491.884767       0.638079     369.241105   
min         0.000000        0.000000       0.000000    -115.000000   
25%         9.000000     4195.000000       3.000000    -114.000000   
50%         9.000000     4195.000000       3.000000    -114.000000   
75%         9.000000     4195.000000       3.000000    -114.000000   
max        45.000000     4195.000000       5.000000   32768.000000   

                args            sus           evil  
count  188967.000000  188967.000000  188967.000000  
mean    22351.441511       0.907349       0.838411  
std      8709.013823       0.289944       0.368074  
min         0.000000       0.000000       0.000000  
25%     17831.000000       1.000000       1.000000  
50%     23610.000000       1.000000       1.000000  
75%     29411.000000       1.000000       1.000000  
max     35176.000000       1.000000       1.000000

# Train Test Split

In [15]:
from sklearn.model_selection import train_test_split
from numpy import mean
from numpy import std
X = data.drop(['sus','evil','hostName','timestamp'], axis = 1)

Y = data['sus']

# Fitting all data as training and testing.
#x_train, y_train = (X, Y)
#x_test, y_test = (X, Y)

In [16]:
# from collections import Counter
# from imblearn.over_sampling import SMOTE
# counter = Counter(Y)
# print('Before', counter)
# smt = SMOTE()
# X, Y = smt.fit_resample(X, Y)
# counter = Counter(Y)
# print('After', counter)

In [17]:
X

processId  threadId  parentProcessId  userId  mountNamespace  \
0             382       382                1     101      4026532232   
1             379       379                1     100      4026532231   
2               1         1                0       0      4026531840   
3               1         1                0       0      4026531840   
4               1         1                0       0      4026531840   
...           ...       ...              ...     ...             ...   
188962       7555      7555             7548    1001      4026531840   
188963       7555      7555             7548    1001      4026531840   
188964       7555      7555             7548    1001      4026531840   
188965       7555      7555             7548    1001      4026531840   
188966       7555      7555             7548    1001      4026531840   

        processName  eventId  eventName  stackAddresses  argsNum  returnValue  \
0                78       41         40            1601        3           15   
1                77       41         40            1158        3           15   
2                73     1005         32            2206        4            0   
3                73      257         28            4195        4           17   
4                73        5         17            2159        2            0   
...             ...      ...        ...             ...      ...          ...   
188962          233       42          9            4195        3         -114   
188963          233       42          9            4195        3         -114   
188964          233       42          9            4195        3         -114   
188965          233       42          9            4195        3         -114   
188966          233       42          9            4195        3         -114   

         args  
0        6912  
1        6912  
2       12213  
3        2628  
4        7099  
...       ...  
188962  25342  
188963  25363  
188964  25385  
188965  25407  
188966  25427  

[188967 rows x 12 columns]

In [18]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.4,random_state = 109) # 80% training and 20% test


In [19]:
x_train_smt = x_train 
x_test_smt = x_test
y_train_smt = y_train 
y_test_smt  = y_test

# SMOTE Balancing

In [20]:
'''from collections import Counter
from imblearn.over_sampling import SMOTE
counter = Counter(y_train)
print('Before', counter)
smt = SMOTE()
x_train_smt, y_train_smt = smt.fit_resample(x_train, y_train)
counter = Counter(y_train_smt)
print('After', counter)'''


"from collections import Counter\nfrom imblearn.over_sampling import SMOTE\ncounter = Counter(y_train)\nprint('Before', counter)\nsmt = SMOTE()\nx_train_smt, y_train_smt = smt.fit_resample(x_train, y_train)\ncounter = Counter(y_train_smt)\nprint('After', counter)"

In [21]:
'''from collections import Counter
from imblearn.over_sampling import SMOTE
counter = Counter(y_test)
print('Before', counter)
smt = SMOTE()
x_test_smt, y_test_smt = smt.fit_resample(x_test, y_test)
counter = Counter(y_test_smt)
print('After', counter)
'''

"from collections import Counter\nfrom imblearn.over_sampling import SMOTE\ncounter = Counter(y_test)\nprint('Before', counter)\nsmt = SMOTE()\nx_test_smt, y_test_smt = smt.fit_resample(x_test, y_test)\ncounter = Counter(y_test_smt)\nprint('After', counter)\n"

# ADASYN - Balancing

In [22]:
"""
from collections import Counter
from imblearn.over_sampling import ADASYN
counter = Counter(y_train)
print('Before', counter)
ada = ADASYN(random_state = 130)
x_train_smt, y_train_smt = ada.fit_resample(x_train, y_train)
counter = Counter(y_train_smt)
print('After', counter)
"""

"\nfrom collections import Counter\nfrom imblearn.over_sampling import ADASYN\ncounter = Counter(y_train)\nprint('Before', counter)\nada = ADASYN(random_state = 130)\nx_train_smt, y_train_smt = ada.fit_resample(x_train, y_train)\ncounter = Counter(y_train_smt)\nprint('After', counter)\n"

In [23]:
"""
from collections import Counter
from imblearn.over_sampling import ADASYN
counter = Counter(y_test)
print('Before', counter)
ada = ADASYN(random_state = 130)
x_test_smt, y_test_smt = ada.fit_resample(x_test, y_test)
counter = Counter(y_test_smt)
print('After', counter)
"""

"\nfrom collections import Counter\nfrom imblearn.over_sampling import ADASYN\ncounter = Counter(y_test)\nprint('Before', counter)\nada = ADASYN(random_state = 130)\nx_test_smt, y_test_smt = ada.fit_resample(x_test, y_test)\ncounter = Counter(y_test_smt)\nprint('After', counter)\n"

# SMOTETomek Balancing

In [24]:
'''
from collections import Counter
from imblearn.combine import SMOTETomek
counter = Counter(y_train)
print('Before', counter)
smtt = SMOTETomek(random_state = 139)
x_train_smt, y_train_smt = smtt.fit_resample(x_train, y_train)
counter = Counter(y_train_smt)
print('After', counter)'''

"\nfrom collections import Counter\nfrom imblearn.combine import SMOTETomek\ncounter = Counter(y_train)\nprint('Before', counter)\nsmtt = SMOTETomek(random_state = 139)\nx_train_smt, y_train_smt = smtt.fit_resample(x_train, y_train)\ncounter = Counter(y_train_smt)\nprint('After', counter)"

In [25]:
'''
from collections import Counter
from imblearn.combine import SMOTETomek
counter = Counter(y_test)
print('Before', counter)
smtt = SMOTETomek(random_state = 139)
x_test_smt, y_test_smt = smtt.fit_resample(x_test, y_test)
counter = Counter(y_test_smt)
print('After', counter)
'''

"\nfrom collections import Counter\nfrom imblearn.combine import SMOTETomek\ncounter = Counter(y_test)\nprint('Before', counter)\nsmtt = SMOTETomek(random_state = 139)\nx_test_smt, y_test_smt = smtt.fit_resample(x_test, y_test)\ncounter = Counter(y_test_smt)\nprint('After', counter)\n"

# Support Vector Classifier Train, Test 

In [26]:
# from sklearn.svm import SVC
# from sklearn.metrics import accuracy_score
# modelSVC = SVC(probability=True)
# modelSVC.fit(x_train_smt, y_train_smt)
# print(modelSVC.score(x_test_smt, y_test_smt))

# y_pred = modelSVC.predict(x_test_smt)
# y_final = y_test
# y_pred_svc = y_pred
# ac = accuracy_score(y_test_smt, y_pred)
# print(ac)

# Performance Measure of SVC

In [27]:
# from sklearn.metrics import confusion_matrix
# from sklearn.metrics import classification_report

# y_pred = modelSVC.predict(x_test_smt)
# print(confusion_matrix(y_test_smt, y_pred))
# print(classification_report(y_test_smt, y_pred))

In [28]:
# from sklearn.metrics import cohen_kappa_score
# cmSVC = confusion_matrix(y_test_smt, modelSVC.predict(x_test_smt))

# #If we use TP TN FP and FN of below's comment we get range
# #FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
# #FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
# #TP = np.diag(cmSVC)
# #TN = cmSVC.sum() - (FP + FN + TP)

# TP = cmSVC[1,1]  
# TN = cmSVC[0,0] 
# FP = cmSVC[0,1] 
# FN = cmSVC[1,0] 

# # Sensitivity, hit rate, recall, or true positive rate
# TPR = TP/float(TP+FN)
# # Specificity or true negative rate
# TNR = TN/float(TN+FP) 
# # Precision or positive predictive value
# PPV = TP/float(TP+FP)
# # Negative predictive value
# NPV = TN/float(TN+FN)
# # Fall out or false positive rate
# FPR = FP/float(FP+TN)
# # False negative rate
# FNR = FN/float(TP+FN)
# # False discovery rate
# FDR = FP/float(TP+FP)
# totalSVC=sum(sum(cmSVC))
# Accuracy = (TN+TP)/totalSVC
# # MCC
# val = (TP * TN) - (FP * FN)
# MCC_SVC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# # Cohen Kappa
# Y_pred = modelSVC.predict(x_test_smt)
# cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

# print("Sensitivity/TPR: " + str(TPR))
# print("FPR: " + str(FPR))
# print("Specificity/TNR: " + str(TNR))
# print("MCC: " + str(MCC_SVC))
# print("Cohen Kappa: " + str(cohen_score))

# AUC Score

In [29]:
# from sklearn.metrics import roc_auc_score

# # predict probabilities
# pred_prob1 = modelSVC.predict_proba(x_test_smt)
# pred_prob2 = modelSVC.predict_proba(x_test_smt)

# # auc scores
# auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
# auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

# print(auc_score1, auc_score2)

# Support Vector Classifier K - Fold CV

In [30]:
# from sklearn.model_selection import cross_val_score
# cv_score_for_SVC = cross_val_score(modelSVC, x_train_smt, y_train_smt, cv = 10)
# cv_score_for_SVC

In [31]:
# print('Accuracy mean and std : %.3f (%.3f)' % (mean(cv_score_for_SVC), std(cv_score_for_SVC)))

In [32]:
# from sklearn.metrics import confusion_matrix
# from sklearn.metrics import classification_report

# y_pred = modelSVC.predict(x_test_smt)
# print(confusion_matrix(y_test_smt, y_pred))
# print(classification_report(y_test_smt, y_pred))

# Decision Tree Classifier Train, Test

In [33]:
from sklearn import tree
from sklearn.metrics import accuracy_score


modelDTC = tree.DecisionTreeClassifier(max_depth=19, min_samples_leaf=9, min_samples_split=10)
modelDTC.fit(x_train_smt, y_train_smt)
print(modelDTC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelDTC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.9994972680487385
0.9994972680487385


# Performance Measure of DTC

In [34]:

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelDTC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[ 6962    26]
 [   12 68587]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6988
           1       1.00      1.00      1.00     68599

    accuracy                           1.00     75587
   macro avg       1.00      1.00      1.00     75587
weighted avg       1.00      1.00      1.00     75587



In [35]:
from sklearn.metrics import cohen_kappa_score
cmDTC = confusion_matrix(y_test_smt, modelDTC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmDTC[1,1]  
TN = cmDTC[0,0] 
FP = cmDTC[0,1] 
FN = cmDTC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalDTC=sum(sum(cmDTC))
Accuracy = (TN+TP)/totalDTC
# MCC
val = (TP * TN) - (FP * FN)
MCC_DTC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelDTC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_DTC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.9998250703363023
FPR: 0.003720663995420721
Specificity/TNR: 0.9962793360045793
MCC: 0.9970019918972812
Cohen Kappa: 0.9970013834865052


# AUC Score

In [36]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelDTC.predict_proba(x_test_smt)
pred_prob2 = modelDTC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9999274401534488 0.9999274401534488


# Random Forest Training and Testing

In [37]:
from sklearn import ensemble
from sklearn.metrics import accuracy_score

modelRFC = ensemble.RandomForestClassifier(n_estimators = 100)
modelRFC.fit(x_train_smt, y_train_smt)
print(modelRFC.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelRFC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)

y_pred_rf = y_pred
print(ac)

0.9999338510590445
0.9999338510590445


# Performance Measure of RFC

In [38]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelRFC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[ 6985     3]
 [    2 68597]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6988
           1       1.00      1.00      1.00     68599

    accuracy                           1.00     75587
   macro avg       1.00      1.00      1.00     75587
weighted avg       1.00      1.00      1.00     75587



In [39]:
from sklearn.metrics import cohen_kappa_score
cmRFC = confusion_matrix(y_test_smt, modelRFC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmRFC[1,1]  
TN = cmRFC[0,0] 
FP = cmRFC[0,1] 
FN = cmRFC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalRFC=sum(sum(cmRFC))
Accuracy = (TN+TP)/totalRFC
# MCC
val = (TP * TN) - (FP * FN)
MCC_RFC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelRFC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_RFC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.9999708450560504
FPR: 0.0004293073840870063
Specificity/TNR: 0.999570692615913
MCC: 0.9996057779398088
Cohen Kappa: 0.9996057748327645


# AUC Score

In [40]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelRFC.predict_proba(x_test_smt)
pred_prob2 = modelRFC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9999999269874758 0.9999999269874758


# Gradient Boosting Classifier Train, Test

In [41]:
from sklearn import ensemble
from sklearn.metrics import accuracy_score

modelGBC = ensemble.GradientBoostingClassifier(max_depth = 3)
modelGBC.fit(x_train_smt, y_train_smt)
print(modelGBC.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelGBC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.9995898765660762
0.9995898765660762


# Performance Measure of GBC

In [42]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelGBC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[ 6975    13]
 [   18 68581]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6988
           1       1.00      1.00      1.00     68599

    accuracy                           1.00     75587
   macro avg       1.00      1.00      1.00     75587
weighted avg       1.00      1.00      1.00     75587



In [43]:
from sklearn.metrics import cohen_kappa_score
cmGBC = confusion_matrix(y_test_smt, modelGBC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmGBC[1,1]  
TN = cmGBC[0,0] 
FP = cmGBC[0,1] 
FN = cmGBC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
#Accuracy
totalGBC=sum(sum(cmGBC))
Accuracy = (TN+TP)/totalGBC
# MCC
val = (TP * TN) - (FP * FN)
MCC_GBC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelGBC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_GBC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.9997376055044535
FPR: 0.0018603319977103605
Specificity/TNR: 0.9981396680022896
MCC: 0.9975568235383807
Cohen Kappa: 0.9975567460812342


# AUC Score

In [44]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelGBC.predict_proba(x_test_smt)
pred_prob2 = modelGBC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9999978054521297 0.9999978054521297


# Logistic Regression Train, Test

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelLR = LogisticRegression()
modelLR.fit(x_train_smt, y_train_smt)
print(modelLR.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelLR.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.9075502401206557
0.9075502401206557


# Performance Measure of LR

In [46]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelLR.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[    0  6988]
 [    0 68599]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      6988
           1       0.91      1.00      0.95     68599

    accuracy                           0.91     75587
   macro avg       0.45      0.50      0.48     75587
weighted avg       0.82      0.91      0.86     75587



In [47]:
from sklearn.metrics import cohen_kappa_score
cmLR = confusion_matrix(y_test_smt, modelLR.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmLR[1,1]  
TN = cmLR[0,0] 
FP = cmLR[0,1] 
FN = cmLR[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalLR=sum(sum(cmLR))
Accuracy = (TN+TP)/totalLR
# MCC
val = (TP * TN) - (FP * FN)
MCC_LR = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelLR.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_LR))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 1.0
FPR: 1.0
Specificity/TNR: 0.0
MCC: nan
Cohen Kappa: 0.0


# AUC Score

In [48]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelLR.predict_proba(x_test_smt)
pred_prob2 = modelLR.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9228726046687311 0.9228726046687311


# KNN Train, Test

In [49]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

modelKNN = KNeighborsClassifier(n_neighbors = 5, weights = 'uniform', metric = 'minkowski', p = 2)
modelKNN.fit(x_train_smt, y_train_smt)
print(modelKNN.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelKNN.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.995647399685131
0.995647399685131


# Performance Measure of KNN

In [50]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelKNN.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[ 6827   161]
 [  168 68431]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      6988
           1       1.00      1.00      1.00     68599

    accuracy                           1.00     75587
   macro avg       0.99      0.99      0.99     75587
weighted avg       1.00      1.00      1.00     75587



In [51]:
from sklearn.metrics import cohen_kappa_score
cmKNN = confusion_matrix(y_test_smt, modelKNN.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmKNN[1,1]  
TN = cmKNN[0,0] 
FP = cmKNN[0,1] 
FN = cmKNN[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalKNN = sum(sum(cmKNN))
Accuracy = (TN+TP)/totalKNN
# MCC
val = (TP * TN) - (FP * FN)
MCC_KNN = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelKNN.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_KNN))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.9975509847082319
FPR: 0.023039496279336005
Specificity/TNR: 0.976960503720664
MCC: 0.9740734619648426
Cohen Kappa: 0.9740733137607976


# AUC Score

In [52]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelKNN.predict_proba(x_test_smt)
pred_prob2 = modelKNN.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9980185005892696 0.9980185005892696


# Stochastic Gradient Descent Train, Test

In [53]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
# loss = 'hinge'
modelSGDC = SGDClassifier(loss = 'log', penalty = "l1", max_iter = 10)
modelSGDC.fit(x_train_smt, y_train_smt)
print(modelSGDC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelSGDC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.913569793747602
0.913569793747602


# Performance Measure of SGDC

In [54]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelSGDC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[ 2514  4474]
 [ 2059 66540]]
              precision    recall  f1-score   support

           0       0.55      0.36      0.43      6988
           1       0.94      0.97      0.95     68599

    accuracy                           0.91     75587
   macro avg       0.74      0.66      0.69     75587
weighted avg       0.90      0.91      0.91     75587



In [55]:
from sklearn.metrics import cohen_kappa_score
cmSGDC = confusion_matrix(y_test_smt, modelSGDC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmSGDC[1,1]  
TN = cmSGDC[0,0] 
FP = cmSGDC[0,1] 
FN = cmSGDC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalSGDC=sum(sum(cmSGDC))
Accuracy = (TN+TP)/totalSGDC
# MCC
val = (TP * TN) - (FP * FN)
MCC_SGDC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelSGDC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_SGDC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.9699849852038659
FPR: 0.6402404121350888
Specificity/TNR: 0.3597595878649113
MCC: 0.40062717868601333
Cohen Kappa: 0.3903198410901543


# AUC Score

In [56]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelSGDC.predict_proba(x_test_smt)
pred_prob2 = modelSGDC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.6648722865343886 0.6648722865343886


# AdaBoost Algorithm Train, Test 

In [57]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

modelABC = AdaBoostClassifier(random_state = 96)
modelABC.fit(x_train_smt, y_train_smt)
print(modelABC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelABC.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)

0.9996427957188405
0.9996427957188405


# Performance Measure of AdaBoost

In [58]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelABC.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[ 6973    15]
 [   12 68587]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6988
           1       1.00      1.00      1.00     68599

    accuracy                           1.00     75587
   macro avg       1.00      1.00      1.00     75587
weighted avg       1.00      1.00      1.00     75587



In [59]:
from sklearn.metrics import cohen_kappa_score
cmABC = confusion_matrix(y_test_smt, modelABC.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmABC[1,1]  
TN = cmABC[0,0] 
FP = cmABC[0,1] 
FN = cmABC[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalABC = sum(sum(cmABC))
Accuracy = (TN+TP)/totalABC

# MCC
val = (TP * TN) - (FP * FN)
MCC_ABC = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))

# Cohen Kappa
Y_pred = modelABC.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_ABC))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.9998250703363023
FPR: 0.0021465369204350317
Specificity/TNR: 0.997853463079565
MCC: 0.9978709383601739
Cohen Kappa: 0.9978709104381285


# AUC Score

In [60]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelABC.predict_proba(x_test_smt)
pred_prob2 = modelABC.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9999977428699661 0.9999977428699661


# AdaBoost Algorithm With K-Fold CV

In [61]:
from sklearn.model_selection import cross_val_score
cv_score_for_ABC = cross_val_score(modelABC, x_train_smt, y_train_smt, cv = 10)
print(cv_score_for_ABC)
print('Accuracy mean and std : %.3f (%.3f)' % (mean(cv_score_for_ABC), std(cv_score_for_ABC)))

[0.9999118  0.99947081 0.9997354  0.9997354  0.9997354  0.9998236
 0.99947081 0.9997354  0.99955901 0.99938261]
Accuracy mean and std : 1.000 (0.000)


# Gaussian Naive Bayes Train Test

In [62]:
# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

modelGNB = GaussianNB()
modelGNB.fit(x_train_smt, y_train_smt)
print(modelGNB.score(x_train_smt, y_train_smt))
# Predicting the Test set results
y_pred = modelGNB.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print(ac)
cm = confusion_matrix(y_test_smt, y_pred)
cm

0.9499118010231081
0.9508645666582878


array([[ 6770,   218],
       [ 3496, 65103]], dtype=int64)

# Gaussian Naive Bayes Performance Measure

In [63]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelGNB.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[ 6770   218]
 [ 3496 65103]]
              precision    recall  f1-score   support

           0       0.66      0.97      0.78      6988
           1       1.00      0.95      0.97     68599

    accuracy                           0.95     75587
   macro avg       0.83      0.96      0.88     75587
weighted avg       0.97      0.95      0.95     75587



In [64]:
from sklearn.metrics import cohen_kappa_score
cmGNB = confusion_matrix(y_test_smt, modelGNB.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmGNB[1,1]  
TN = cmGNB[0,0] 
FP = cmGNB[0,1] 
FN = cmGNB[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalGNB=sum(sum(cmGNB))
Accuracy = (TN+TP)/totalGNB
# MCC
val = (TP * TN) - (FP * FN)
MCC_GNB = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelGNB.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_GNB))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.9490371579760638
FPR: 0.031196336576989125
Specificity/TNR: 0.9688036634230108
MCC: 0.776024919597257
Cohen Kappa: 0.758137329695707


In [65]:
from sklearn.model_selection import cross_val_score
cv_score_for_xgb= cross_val_score(modelGNB, x_train_smt, y_train_smt, cv = 10)
print(cv_score_for_xgb)
print('Accuracy mean and std : %.3f (%.3f)' % (mean(cv_score_for_xgb), std(cv_score_for_xgb)))

[0.94778621 0.95122597 0.94946199 0.95007938 0.95201976 0.95281355
 0.94858    0.95193156 0.94963838 0.94893279]
Accuracy mean and std : 0.950 (0.002)


# AUC Score

In [66]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelGNB.predict_proba(x_test_smt)
pred_prob2 = modelGNB.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9873454943383043 0.9873454943383043


## XGBoost

In [67]:
# Training the Naive Bayes model on the Training set
import xgboost as xgb
from sklearn.metrics import accuracy_score

modelXGB = xgb.XGBClassifier()

modelXGB.fit(x_train_smt, y_train_smt)
print('Training',modelXGB.score(x_train_smt, y_train_smt))
# Predicting the Test set results
y_pred = modelXGB.predict(x_test_smt)
ac = accuracy_score(y_test_smt, y_pred)
print('Testing',ac)
cm = confusion_matrix(y_test_smt, y_pred)
cm

Training 1.0
Testing 0.9999735404236179


array([[ 6987,     1],
       [    1, 68598]], dtype=int64)

In [68]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelXGB.predict(x_test_smt)
print(confusion_matrix(y_test_smt, y_pred))
print(classification_report(y_test_smt, y_pred))

[[ 6987     1]
 [    1 68598]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6988
           1       1.00      1.00      1.00     68599

    accuracy                           1.00     75587
   macro avg       1.00      1.00      1.00     75587
weighted avg       1.00      1.00      1.00     75587



In [69]:
from sklearn.metrics import cohen_kappa_score
cmGNB = confusion_matrix(y_test_smt, modelXGB.predict(x_test_smt))

#If we use TP TN FP and FN of below's comment we get range
#FP = cmSVC.sum(axis=0) - np.diag(cmSVC)  
#FN = cmSVC.sum(axis=1) - np.diag(cmSVC)
#TP = np.diag(cmSVC)
#TN = cmSVC.sum() - (FP + FN + TP)

TP = cmGNB[1,1]  
TN = cmGNB[0,0] 
FP = cmGNB[0,1] 
FN = cmGNB[1,0] 

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/float(TP+FN)
# Specificity or true negative rate
TNR = TN/float(TN+FP) 
# Precision or positive predictive value
PPV = TP/float(TP+FP)
# Negative predictive value
NPV = TN/float(TN+FN)
# Fall out or false positive rate
FPR = FP/float(FP+TN)
# False negative rate
FNR = FN/float(TP+FN)
# False discovery rate
FDR = FP/float(TP+FP)
# Accuracy
totalGNB=sum(sum(cmGNB))
Accuracy = (TN+TP)/totalGNB
# MCC
val = (TP * TN) - (FP * FN)
MCC_GNB = val / np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
# Cohen Kappa
Y_pred = modelXGB.predict(x_test_smt)
cohen_score = cohen_kappa_score(y_test_smt, Y_pred)

print("Sensitivity/TPR: " + str(TPR))
print("FPR: " + str(FPR))
print("Specificity/TNR: " + str(TNR))
print("MCC: " + str(MCC_GNB))
print("Cohen Kappa: " + str(cohen_score))

Sensitivity/TPR: 0.9999854225280251
FPR: 0.00014310246136233542
Specificity/TNR: 0.9998568975386377
MCC: 0.9998423200666628
Cohen Kappa: 0.9998423200666628


In [70]:
from sklearn.metrics import roc_auc_score

# predict probabilities
pred_prob1 = modelXGB.predict_proba(x_test_smt)
pred_prob2 = modelXGB.predict_proba(x_test_smt)

# auc scores
auc_score1 = roc_auc_score(y_test_smt, pred_prob1[:,1])
auc_score2 = roc_auc_score(y_test_smt, pred_prob2[:,1])

print(auc_score1, auc_score2)

0.9999997601017062 0.9999997601017062
